###
http://localhost:3000/users

###
GET http://localhost:3000/users/1

###
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
  "cargo": "gerente",
  "username": "email@gmail.com",
  "senha": "001122",
  "admin": "sim",
  "status": "inativo"
}

###
PUT http://localhost:3000/users/2 HTTP/1.1
Content-Type: application/json

 {
  "cargo": "teste",
  "username": "email@gmail.com",
  "senha": "001122",
  "admin": "sim",
  "status": "inativo"
}

###
DELETE  http://localhost:3000/users/5
